name: app
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - rdkit
  - numpy
  - pandas
  - scikit-learn
  - pip:
      - fastapi
      - uvicorn[standard]
      - pydantic
      - langchain
      - langchain-google-genai
      - python-dotenv
      - diskcache==5.6.3
      - requests
      - Pillow
